apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  labels:
    apps.tanzu.vmware.com/pipeline: test
  name: developer-defined-tekton-pipeline
  namespace: my-apps
spec:
  params:
  - name: source-url
    type: string
  - name: source-revision
    type: string
  tasks:
  - name: test
    params:
    - name: source-url
      value: $(params.source-url)
    - name: source-revision
      value: $(params.source-revision)
    taskSpec:
      metadata: {}
      params:
      - name: source-url
        type: string
      - name: source-revision
        type: string
      spec: null
      steps:
      - computeResources: {}
        image: gradle
        name: test
        script: |
          cd `mktemp -d`
          wget -qO- $(params.source-url) | tar xvz -m
          ./mvnw -X test --no-transfer-progress